### ISSUE TITLE
How do you export to a video?

### ISSUE THREAD

**Issue by kevinlinxc** [groussea/opyflow#2]
I've copied the Navizence example to my notebook, and entered my own video. I'm confused at how to export to frames or to a video, however. Could you explain if this is possible? I'm talking specifically about how to make a video just like the ones in the readme.

**Comment by groussea** [comment]
Sorry for the late answer. The video in the Readme is a succession of images. You can create the images using the saveImgPath option during the extraction process from the Analyzer object or directly by saving the images from the figure function video.opyfDisp.fig.savefig("folder") as done, for instance, here https://github.com/groussea/opyflow/blob/master/tests/Test_Navizence/gif/test_opyf_Navizence_generate_gif.py. From images, you can create a _gif_ or a _video_ using, for instance, the classical ffmpeg library.
