### ISSUE TITLE
Set Region of Interest

### ISSUE THREAD

**Issue by belaskrn** [groussea/opyflow#4]
Ive applied opyflow to process a sequence of images from my own video. Im trying to understand how to change the region of interest to focus on a specific part to process. How do i achieve that? Thank you in advance.

**Comment by groussea** [comment]
Hi, Sorry for my late answer. To set the region of interest (ROI), you can simply add the imageROI argument when generating the Analyzer object.
Here, regarding the [Navizence example](https://github.com/groussea/opyflow/blob/master/tests/Test_Navizence/opyf_Navizence_velocimetry_UAV.md) , if you type the following when creating the video object:

`video=opyf.videoAnalyzer('./2018.07.04_Station_fixe_30m_sample.mp4', imageROI=[100, 100, 1000, 800])`

It will focus on the ROI = [leftPx, upPx, width, height] = [100, 100, 1000, 800] as shown in this screenshot:

![image](https://github.com/groussea/opyflow/assets/34556608/ef78d178-23e9-4e4d-8784-5d3d5ebff8bd)


With the ROI represented here in Red:

![image](https://github.com/groussea/opyflow/assets/34556608/367baf74-614c-4a3d-ad22-13dfa3580886)

**Comment by belaskrn** [comment]
Thank you!
